name: Frank1 Auto Update M3U File

on:
  schedule:
    - cron: "0 */6 * * *"  # 每6小时触发一次
  workflow_dispatch:  # 手动触发选项

jobs:
  update-m3u:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download M3U file from URL
        run: |
          echo "Downloading file from http://niu66.vip/Z8PMac..."
          curl -L -o frank1.m3u "http://niu66.vip/Z8PMac"
          echo "Download completed."

      - name: Remove expiration lines
        run: |
          echo "Removing lines with expiration dates..."
          sed -i '/到期时间/d' frank1.m3u
          echo "Lines with expiration dates removed."

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add frank1.m3u
          git commit -m "Auto update frank1.m3u and remove expiration lines"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
