name: Auto Update M3U File

on:
  schedule:
    - cron: "*/1 * * * *"  # 每分钟触发一次
  workflow_dispatch:  # 手动触发选项

jobs:
  update-m3u:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download M3U file from URL
        run: |
          echo "Downloading file from http://niu66.vip/4qq71F..."
          curl -L -o 4qq71F.m3u "http://niu66.vip/4qq71F"
          echo "Download completed."

      - name: Replace the M3U file in repository
        run: |
          mv 4qq71F.m3u 4qq71F.m3u
          echo "M3U file replaced in repository."

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add 4qq71F.m3u
          git commit -m "Auto update 4qq71F.m3u from http://niu66.vip/4qq71F"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
