name: Auto Update and Periodic Delete M3U File

on:
  schedule:
    - cron: "0 */6 * * *"  # 每 6 小时触发一次，更新文件
    - cron: "35 14 13 * *" # 每月 13 号下午 14:50 触发，删除文件
  workflow_dispatch:  # 手动触发选项

jobs:
  manage-m3u:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Execute Task
        run: |
          if [[ "${{ github.event.schedule }}" == "*/1 * * * *" ]]; then
            echo "Downloading M3U file..."
            curl -L -o file.m3u "http://niu66.vip/Z8PMac"
            git add file.m3u
            git commit -m "Auto update file.m3u from http://niu66.vip/Z8PMac" || echo "No changes to commit"
          elif [[ "${{ github.event.schedule }}" == "0 0 1 * *" ]]; then
            echo "Deleting M3U file..."
            rm -f 20250213.m3u
            git add .
            git commit -m "Remove file.m3u after one month" || echo "No changes to commit"
          fi
      - name: Push Changes
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
